# Generated by Django 2.2.2 on 2019-06-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190616_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='categories',
        ),
        migrations.AddField(
            model_name='customuser',
            name='business',
            field=models.BooleanField(default=False),
        ),
    ]
