# Generated by Django 2.2.2 on 2019-07-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190617_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='health',
            field=models.BooleanField(default=False),
        ),
    ]
