# Generated by Django 2.2.2 on 2019-07-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='usa',
            field=models.BooleanField(default=False),
        ),
    ]
