# Generated by Django 2.2.2 on 2019-07-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_usa'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='style',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='travel',
            field=models.BooleanField(default=False),
        ),
    ]
