# Generated by Django 2.2.2 on 2019-07-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190715_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='opinion',
            field=models.BooleanField(default=False),
        ),
    ]
