# Generated by Django 2.2.2 on 2019-07-18 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_opinion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='politics',
        ),
    ]
