# Generated by Django 2.2.2 on 2019-07-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_customuser_politics'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=1000)),
                ('body', models.TextField()),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=250)),
            ],
        ),
    ]
