# Generated by Django 2.2.2 on 2019-07-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(default='health', max_length=250),
            preserve_default=False,
        ),
    ]
