# Generated by Django 2.2.2 on 2019-07-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190718_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='posttime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
